---
- name: test if upgrade_packages is set correctly
  assert:
    that:
      - upgrade_packages | length > 0
      - upgrade_packages is iterable
  when:
    - upgrade_packages is defined

- name: test if item in upgrade_packages is set correctly
  assert:
    that:
      - item is defined
      - item | length > 0
  loop: "{{ upgrade_packages }}"
  when:
    - upgrade_packages is defined
